name: Andrew Marsee, Data Scientist
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
title                    : "Andrew Marsee Portfolio"
title_separator          : "-"
name                     : "Andrew Marsee"
description              : "Showcasing the work of Andrew Marsee"
url                      : https://andrewmarsee.com

theme: jekyll-theme-minimal
plugins:
  - jekyll-archive
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-archive
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  
# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :
naver-site-verification  :


analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: "UA-137786150-1"

# Site Author
author:
  name             : "Andrew Marsee"
  avatar           : 
  bio              : "Data Analyst"
  location         : "Nashville"
  email            :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : amarsee
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : andrew_marsee
  lastfm           :
  linkedin         : amarsee # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          : andrew_marsee
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"
